const fs = require('fs');

const raw = [
  ["Playboi Carti", "Sky", "Whole Lotta Red"],
  ["Playboi Carti", "Stop Breathing", "Whole Lotta Red"],
  ["Playboi Carti", "Magnolia", "Playboi Carti"],
  ["Playboi Carti, Lil Uzi Vert", "wokeuplikethis*", "Playboi Carti"],
  ["Playboi Carti", "Shoota", "Die Lit"],
  ["Playboi Carti", "R.I.P.", "Die Lit"],
  ["Playboi Carti", "Fell In Luv", "Die Lit"],
  ["Playboi Carti", "ILoveUIHateU", "Whole Lotta Red"],
  ["Playboi Carti", "Vamp Anthem", "Whole Lotta Red"],
  ["Playboi Carti", "New N3on", "Whole Lotta Red"],
  ["Ken Carson", "Yale", "Teen X"],
  ["Ken Carson", "Fighting My Demons", "A Great Chaos"],
  ["Ken Carson", "overseas", "A Great Chaos (Deluxe)"],
  ["Ken Carson", "Jennifer’s Body", "A Great Chaos"],
  ["Ken Carson", "Freestyle 2", "X"],
  ["Ken Carson", "Rock N Roll", "Project X"],
  ["Ken Carson", "ss", "A Great Chaos (Deluxe)"],
  ["Ken Carson", "me n my kup", "A Great Chaos"],
  ["Ken Carson", "i need u", "i need u — Single"],
  ["Ken Carson", "Delusional", "More Chaos"],
  ["Destroy Lonely", "NOSTYLIST", "NO STYLIST"],
  ["Destroy Lonely", "if looks could kill", "If Looks Could Kill"],
  ["Destroy Lonely", "Bane", "</3²"],
  ["Destroy Lonely", "how u feel?", "If Looks Could Kill"],
  ["Destroy Lonely", "VTMNTSCOAT", "NO STYLIST"],
  ["Destroy Lonely", "CRYSTLCSTLES", "NO STYLIST"],
  ["Destroy Lonely", "TURNINUP", "NS+ (ULTRA)"],
  ["Destroy Lonely", "NEVEREVER", "If Looks Could Kill"],
  ["Destroy Lonely", "LOUVRE", "If Looks Could Kill"],
  ["Young Thug", "Hot", "So Much Fun"],
  ["Young Thug, J. Cole, Travis Scott", "The London", "So Much Fun"],
  ["Young Thug", "Check", "Barter 6"],
  ["Young Thug", "Digits", "Slime Season 3"],
  ["Young Thug", "Best Friend", "Slime Season"],
  ["Young Thug", "With That", "Barter 6"],
  ["Young Stoner Life, Young Thug, Gunna", "Ski", "Slime Language 2"],
  ["Young Stoner Life, Young Thug, Gunna, Drake", "Solid", "Slime Language 2"],
  ["Gunna", "fukumean", "a Gift & a Curse"],
  ["Lil Baby, Gunna", "Drip Too Hard", "Drip Harder"],
  ["Gunna, Future, Young Thug", "pushin P", "DS4EVER"],
  ["Gunna", "one of wun", "One of Wun"],
  ["Gunna", "Banking On Me", "Banking On Me — Single"],
  ["Gunna", "bread & butter", "a Gift & a Curse"],
  ["Gunna, Future", "too easy", "DS4EVER"],
  ["Gunna", "rodeo dr", "a Gift & a Curse"],
  ["Lil Baby", "Freestyle", "Too Hard"],
  ["Lil Baby, Drake", "Yes Indeed", "Harder Than Ever"],
  ["Lil Baby", "Woah", "My Turn"],
  ["Lil Baby", "Emotionally Scarred", "My Turn"],
  ["Lil Baby", "Sum 2 Prove", "My Turn"],
  ["Lil Baby", "In A Minute", "It’s Only Me"],
  ["Lil Baby", "California Breeze", "It’s Only Me"],
  ["Lil Baby", "On Me", "On Me — Single"],
  ["Future, Metro Boomin, Kendrick Lamar", "Like That", "WE DON’T TRUST YOU"],
  ["Future, Metro Boomin, Travis Scott, Playboi Carti", "Type Shit", "WE DON’T TRUST YOU"],
  ["Future, Drake, Tems", "WAIT FOR U", "I NEVER LIKED YOU"],
  ["Future", "Mask Off", "FUTURE"],
  ["Future", "March Madness", "56 Nights"],
  ["Future", "PUFFIN ON ZOOTIEZ", "I NEVER LIKED YOU"],
  ["Future, Metro Boomin, Travis Scott", "Cinderella", "WE DON’T TRUST YOU"],
  ["Travis Scott, Playboi Carti", "FE!N", "UTOPIA"],
  ["Travis Scott", "I KNOW ?", "UTOPIA"],
  ["Travis Scott", "SICKO MODE", "ASTROWORLD"],
  ["Travis Scott", "goosebumps", "Birds in the Trap Sing McKnight"],
  ["Travis Scott", "HIGHEST IN THE ROOM", "HIGHEST IN THE ROOM — Single"],
  ["Drake, 21 Savage", "Rich Flex", "Her Loss"],
  ["Drake, J. Cole", "First Person Shooter", "For All The Dogs"],
  ["Drake", "Nonstop", "Scorpion"],
  ["Drake, 21 Savage, Project Pat", "Knife Talk", "Certified Lover Boy"],
  ["Disclosure, Sam Smith", "Latch", "Settle"],
  ["Disclosure, AlunaGeorge", "White Noise", "Settle"],
  ["Disclosure, Eliza Doolittle", "You & Me", "Settle"],
  ["Route 94, Jess Glynne", "My Love", "My Love — Single"],
  ["Chris Lake, Aatig", "In The Yuma", "In The Yuma — Single"],
  ["Chris Lake, Aluna", "More Baby", "More Baby — Single"],
];

function norm(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

const ALBUM_COVER = {
  wholelottared: `/covers/wholelottared-coverart.jpeg`,
  playboicarti: `/covers/playboicarti-selftitled-coverart.jpeg`,
  dielit: `/covers/dielit-coverart.jpeg`,
  teenx: `/covers/kencarson-teenx-coverart.jpeg`,
  agreatchaos: `/covers/kencarsonagreatchaos-coverart.jpeg`,
  agreatchaosdeluxe: `/covers/kencarsonagreatchaos-coverart.jpeg`,
  x: `/covers/kencarsonX-coverart.jpeg`,
  ineedu: `/covers/kencarson-ineedu-coverart.jpeg`,
  ineedusingle: `/covers/kencarson-ineedu-coverart.jpeg`,
  morechaos: `/covers/kencarsonmorechaos-coverart.jpeg`,
  nostylist: `/covers/nostylist-coverart.jpeg`,
  iflookscouldkill: `/covers/iflookscouldkill-coverart.jpeg`,
  32: `/covers/destroylonely<:32-coverart.jpeg`,
  nsultra: `/covers/destroylonelynsultra-coverart.jpeg`,
  somuchfun: `/covers/somuchfun-coverart.jpeg`,
  barter6: `/covers/barter6-coverart.jpeg`,
  slimeseason3: `/covers/slimeseason3-coverart.jpeg`,
  slimeseason2: `/covers/slimeseason2-coverart.jpeg`,
  slimelanguage2: `/covers/slimelanguage2-coverart.jpeg`,
  agiftacurse: `/covers/gunnagiftandcurse-coverart.jpeg`,
  dripharder: `/covers/gunnadripharder.jpeg`,
  ds4ever: `/covers/gunnads4ever-coverart.jpeg`,
  oneofwun: `/covers/gunnaoneofwun-coverart.jpeg`,
  bankingonmesingle: `/covers/gunnabankingonme-coverart.jpeg`,
  toohard: `/covers/lilbabytoohard-coverart.jpeg`,
  harderthanever: `/covers/lilbabyharderthanever-coverart.jpeg`,
  myturn: `/covers/lilbabymyturn-coverart.jpeg`,
  itsonlyme: `/covers/lilbabyitsonlyme-coverart.jpeg`,
  wedonttrustyou: `/covers/futurewedonttrustyou-coverart.jpeg`,
  ineverlikedyou: `/covers/futureineverlikedyou-coverart.jpeg`,
  future: `/covers/futuremaskoff-future-coverart.jpeg`,
  "56nights": `/covers/future56nights-coverart.jpeg`,
  utopia: `/covers/travisscott-utopia.jpeg`,
  astroworld: `/covers/travisscottastroworld-coverart.jpeg`,
  birdsinthetrapsingmcknight: `/covers/travisscott-goosebumps-birdsinthetrap-coverart.jpeg`,
  highestintheroomsingle: `/covers/travisscotthighestintheroom-coverart.jpeg`,
  herloss: `/covers/drakeherloss.jpeg`,
  forallthedogs: `/covers/drakeforallthedogs-coverart.jpeg`,
  scorpion: `/covers/drakescorpion-coverart.jpeg`,
  certifiedloverboy: `/covers/drakecertifiedloverboy-coverart.jpeg`,
  settle: `/covers/disclosuresettle-coverart.jpeg`,
  mylovesingle: `/covers/route94mylove-coverart.jpeg`,
  intheyumasingle: `/covers/chrislake-yuma-coverart.jpeg`,
  morebabysingle: `/covers/chrislake-morebaby-coverart.jpeg`,
};

const missing = [];
for (const [artist, title, album] of raw) {
  const k = norm(album);
  if (!ALBUM_COVER[k]) {
    missing.push({artist, title, album, key: k});
  }
}
console.log("Missing from ALBUM_COVER mapping:", missing);

