import type { OrganizationMember } from './mockEventsData';

/** Georgetown Program Board roster — 48 members across Exec / Programming / Marketing / Production. */
export const GPB_ROSTER: OrganizationMember[] = [
  // EXEC BOARD — 8
  {
    org: 'program_board',
    subgroup: 'exec-board',
    name: 'Cole Brennan',
    title: 'President',
    email: 'cole.brennan@georgetown.edu',
    phone: '202-555-0105',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'exec-board',
    name: 'Daniel Kim',
    title: 'Vice President',
    email: 'daniel.kim@georgetown.edu',
    phone: '202-555-0102',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'exec-board',
    name: 'Sofia Martinez',
    title: 'Finance Chair',
    email: 'sofia.martinez@georgetown.edu',
    phone: '202-555-0103',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'exec-board',
    name: 'Noah Williams',
    title: 'Membership Chair',
    email: 'noah.williams@georgetown.edu',
    phone: '202-555-0104',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'exec-board',
    name: 'Maya Thompson',
    title: 'Concerts Chair',
    email: 'maya.thompson@georgetown.edu',
    phone: '202-555-0101',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'exec-board',
    name: 'Amara Okafor',
    title: 'Georgetown Day Chair',
    email: 'amara.okafor@georgetown.edu',
    phone: '202-555-0106',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'exec-board',
    name: "Liam O'Connor",
    title: 'Special Events Chair',
    email: 'liam.oconnor@georgetown.edu',
    phone: '202-555-0107',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'exec-board',
    name: 'Priya Shah',
    title: 'Marketing Chair',
    email: 'priya.shah@georgetown.edu',
    phone: '202-555-0108',
    status: 'joined',
  },

  // PROGRAMMING — 14
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Elena Rossi',
    title: 'Programming Committee Lead',
    email: 'elena.rossi@georgetown.edu',
    phone: '202-555-0109',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Marcus Reed',
    title: null,
    email: 'marcus.reed@georgetown.edu',
    phone: '202-555-0110',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Grace Park',
    title: null,
    email: 'grace.park@georgetown.edu',
    phone: '202-555-0111',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Ethan Caldwell',
    title: null,
    email: 'ethan.caldwell@georgetown.edu',
    phone: '202-555-0112',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Aaliyah Johnson',
    title: null,
    email: 'aaliyah.johnson@georgetown.edu',
    phone: '202-555-0113',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Julian Brooks',
    title: null,
    email: 'julian.brooks@georgetown.edu',
    phone: '202-555-0114',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Natalie Chen',
    title: null,
    email: 'natalie.chen@georgetown.edu',
    phone: '202-555-0115',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Caleb Foster',
    title: null,
    email: 'caleb.foster@georgetown.edu',
    phone: '202-555-0116',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Isabella Ramirez',
    title: null,
    email: 'isabella.ramirez@georgetown.edu',
    phone: '202-555-0117',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Owen Sullivan',
    title: null,
    email: 'owen.sullivan@georgetown.edu',
    phone: '202-555-0118',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Zara Ahmed',
    title: null,
    email: 'zara.ahmed@georgetown.edu',
    phone: '202-555-0119',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Miles Harrington',
    title: null,
    email: 'miles.harrington@georgetown.edu',
    phone: '202-555-0120',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Camila Torres',
    title: null,
    email: 'camila.torres@georgetown.edu',
    phone: '202-555-0121',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'programming',
    name: 'Benjamin Nolan',
    title: null,
    email: 'benjamin.nolan@georgetown.edu',
    phone: '202-555-0122',
    status: 'not_on_ligo',
  },

  // MARKETING — 12
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Chloe Anderson',
    title: 'Creative Lead',
    email: 'chloe.anderson@georgetown.edu',
    phone: '202-555-0123',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Isaac Patel',
    title: null,
    email: 'isaac.patel@georgetown.edu',
    phone: '202-555-0124',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Nina Desai',
    title: null,
    email: 'nina.desai@georgetown.edu',
    phone: '202-555-0125',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Jack Murphy',
    title: null,
    email: 'jack.murphy@georgetown.edu',
    phone: '202-555-0126',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Layla Hassan',
    title: null,
    email: 'layla.hassan@georgetown.edu',
    phone: '202-555-0127',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Henry Walsh',
    title: null,
    email: 'henry.walsh@georgetown.edu',
    phone: '202-555-0128',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Victoria Nguyen',
    title: null,
    email: 'victoria.nguyen@georgetown.edu',
    phone: '202-555-0129',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Samuel Price',
    title: null,
    email: 'samuel.price@georgetown.edu',
    phone: '202-555-0130',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Ruby Goldstein',
    title: null,
    email: 'ruby.goldstein@georgetown.edu',
    phone: '202-555-0131',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Adrian Rivera',
    title: null,
    email: 'adrian.rivera@georgetown.edu',
    phone: '202-555-0132',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Mia Collins',
    title: null,
    email: 'mia.collins@georgetown.edu',
    phone: '202-555-0133',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'marketing',
    name: 'Theo Papadopoulos',
    title: null,
    email: 'theo.papadopoulos@georgetown.edu',
    phone: '202-555-0134',
    status: 'not_on_ligo',
  },

  // PRODUCTION — 14
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Jordan Davis',
    title: 'Event Operations Lead',
    email: 'jordand@georgetown.edu',
    phone: '202-555-0135',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Madeline Lee',
    title: null,
    email: 'madeline.lee@georgetown.edu',
    phone: '202-555-0136',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Connor McCarthy',
    title: null,
    email: 'connor.mccarthy@georgetown.edu',
    phone: '202-555-0137',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Fatima Rahman',
    title: null,
    email: 'fatima.rahman@georgetown.edu',
    phone: '202-555-0138',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Lucas Moretti',
    title: null,
    email: 'lucas.moretti@georgetown.edu',
    phone: '202-555-0139',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Sydney Turner',
    title: null,
    email: 'sydney.turner@georgetown.edu',
    phone: '202-555-0140',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Malik Washington',
    title: null,
    email: 'malik.washington@georgetown.edu',
    phone: '202-555-0141',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Audrey Sinclair',
    title: null,
    email: 'audrey.sinclair@georgetown.edu',
    phone: '202-555-0142',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Thomas Greene',
    title: null,
    email: 'thomas.greene@georgetown.edu',
    phone: '202-555-0143',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Leila Nasser',
    title: null,
    email: 'leila.nasser@georgetown.edu',
    phone: '202-555-0144',
    status: 'joined',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Gavin Ross',
    title: null,
    email: 'gavin.ross@georgetown.edu',
    phone: '202-555-0145',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Serena Wu',
    title: null,
    email: 'serena.wu@georgetown.edu',
    phone: '202-555-0146',
    status: 'not_on_ligo',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Nathaniel Clark',
    title: null,
    email: 'nathaniel.clark@georgetown.edu',
    phone: '202-555-0147',
    status: 'invited',
  },
  {
    org: 'program_board',
    subgroup: 'production',
    name: 'Gabriella Santos',
    title: null,
    email: 'gabriella.santos@georgetown.edu',
    phone: '202-555-0148',
    status: 'not_on_ligo',
  },
];

export const GPB_MEMBER_GROUPS = [
  { id: 'exec-board', title: 'EXEC BOARD' },
  { id: 'programming', title: 'PROGRAMMING' },
  { id: 'marketing', title: 'MARKETING' },
  { id: 'production', title: 'PRODUCTION' },
] as const;
