import type { OrganizationMember } from './mockEventsData';

/** Sigma Alpha Epsilon roster — 74 members across Exec / Brothers / New Members. Alumni are reachable for invites but not listed. */
export const SAE_ROSTER: OrganizationMember[] = [
  // EXEC BOARD — 8
  {
    org: 'sae',
    subgroup: 'exec-board',
    name: 'Cole Brennan',
    title: 'Social Chair',
    email: 'cole.brennan@georgetown.edu',
    phone: '202-555-0105',
    status: 'joined',
  },
  {
    org: 'sae',
    subgroup: 'exec-board',
    name: 'Reid Vandenberg',
    title: 'President',
    email: 'reid.vandenberg@georgetown.edu',
    phone: '202-555-0301',
    status: 'joined',
  },
  {
    org: 'sae',
    subgroup: 'exec-board',
    name: 'Miles Thackeray',
    title: 'Vice President',
    email: 'miles.thackeray@georgetown.edu',
    phone: '202-555-0302',
    status: 'joined',
  },
  {
    org: 'sae',
    subgroup: 'exec-board',
    name: 'Grant Ellsworth',
    title: 'Treasurer',
    email: 'grant.ellsworth@georgetown.edu',
    phone: '202-555-0303',
    status: 'invited',
  },
  {
    org: 'sae',
    subgroup: 'exec-board',
    name: 'Owen Marchetti',
    title: 'Recruitment Chair',
    email: 'owen.marchetti@georgetown.edu',
    phone: '202-555-0304',
    status: 'joined',
  },
  {
    org: 'sae',
    subgroup: 'exec-board',
    name: 'Beau Lindqvist',
    title: 'Brotherhood Chair',
    email: 'beau.lindqvist@georgetown.edu',
    phone: '202-555-0305',
    status: 'joined',
  },
  {
    org: 'sae',
    subgroup: 'exec-board',
    name: 'Tate Kowalczyk',
    title: 'Risk Manager',
    email: 'tate.kowalczyk@georgetown.edu',
    phone: '202-555-0306',
    status: 'invited',
  },
  {
    org: 'sae',
    subgroup: 'exec-board',
    name: 'Sawyer Delacroix',
    title: 'Philanthropy Chair',
    email: 'sawyer.delacroix@georgetown.edu',
    phone: '202-555-0307',
    status: 'not_on_ligo',
  },

  // BROTHERS — 52
  { org: 'sae', subgroup: 'brothers', name: 'Callum Rhodes', title: null, email: 'callum.rhodes@georgetown.edu', phone: '202-555-0310', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Declan Whitfield', title: null, email: 'declan.whitfield@georgetown.edu', phone: '202-555-0311', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Emmett Vasquez', title: null, email: 'emmett.vasquez@georgetown.edu', phone: '202-555-0312', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Finn Okonkwo', title: null, email: 'finn.okonkwo@georgetown.edu', phone: '202-555-0313', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Graham Sutcliffe', title: null, email: 'graham.sutcliffe@georgetown.edu', phone: '202-555-0314', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Hayes Bellamy', title: null, email: 'hayes.bellamy@georgetown.edu', phone: '202-555-0315', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Ira Nakamura', title: null, email: 'ira.nakamura@georgetown.edu', phone: '202-555-0316', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Jasper Lowell', title: null, email: 'jasper.lowell@georgetown.edu', phone: '202-555-0317', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Knox Abernathy', title: null, email: 'knox.abernathy@georgetown.edu', phone: '202-555-0318', status: 'sms-pending' },
  { org: 'sae', subgroup: 'brothers', name: 'Landon Pierce', title: null, email: 'landon.pierce@georgetown.edu', phone: '202-555-0319', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Mateo Salazar', title: null, email: 'mateo.salazar@georgetown.edu', phone: '202-555-0320', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Nash Kirkland', title: null, email: 'nash.kirkland@georgetown.edu', phone: '202-555-0321', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Oscar Beaumont', title: null, email: 'oscar.beaumont@georgetown.edu', phone: '202-555-0322', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Porter Hendricks', title: null, email: 'porter.hendricks@georgetown.edu', phone: '202-555-0323', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Quinn Gallagher', title: null, email: 'quinn.gallagher@georgetown.edu', phone: '202-555-0324', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Rhett Donovan', title: null, email: 'rhett.donovan@georgetown.edu', phone: '202-555-0325', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Silas Ferraro', title: null, email: 'silas.ferraro@georgetown.edu', phone: '202-555-0326', status: 'sms-pending' },
  { org: 'sae', subgroup: 'brothers', name: 'Thatcher Nolan', title: null, email: 'thatcher.nolan@georgetown.edu', phone: '202-555-0327', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Uriah Blackwood', title: null, email: 'uriah.blackwood@georgetown.edu', phone: '202-555-0328', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Vaughn Castellano', title: null, email: 'vaughn.castellano@georgetown.edu', phone: '202-555-0329', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Wells Ashford', title: null, email: 'wells.ashford@georgetown.edu', phone: '202-555-0330', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Xavier Mbeki', title: null, email: 'xavier.mbeki@georgetown.edu', phone: '202-555-0331', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Yusuf Karim', title: null, email: 'yusuf.karim@georgetown.edu', phone: '202-555-0332', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Zane Prescott', title: null, email: 'zane.prescott@georgetown.edu', phone: '202-555-0333', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Archer Halloran', title: null, email: 'archer.halloran@georgetown.edu', phone: '202-555-0334', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Bodhi Tran', title: null, email: 'bodhi.tran@georgetown.edu', phone: '202-555-0335', status: 'sms-pending' },
  { org: 'sae', subgroup: 'brothers', name: 'Cassius Moreau', title: null, email: 'cassius.moreau@georgetown.edu', phone: '202-555-0336', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Dashiell Grimaldi', title: null, email: 'dashiell.grimaldi@georgetown.edu', phone: '202-555-0337', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Everett Sandoval', title: null, email: 'everett.sandoval@georgetown.edu', phone: '202-555-0338', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Ford Winslow', title: null, email: 'ford.winslow@georgetown.edu', phone: '202-555-0339', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Gideon Alvarez', title: null, email: 'gideon.alvarez@georgetown.edu', phone: '202-555-0340', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Harlan Pruitt', title: null, email: 'harlan.pruitt@georgetown.edu', phone: '202-555-0341', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Ivan Petrov', title: null, email: 'ivan.petrov@georgetown.edu', phone: '202-555-0342', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Jonah Kensington', title: null, email: 'jonah.kensington@georgetown.edu', phone: '202-555-0343', status: 'sms-pending' },
  { org: 'sae', subgroup: 'brothers', name: 'Kai Fitzgerald', title: null, email: 'kai.fitzgerald@georgetown.edu', phone: '202-555-0344', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Lachlan Boyd', title: null, email: 'lachlan.boyd@georgetown.edu', phone: '202-555-0345', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Malcolm Sterling', title: null, email: 'malcolm.sterling@georgetown.edu', phone: '202-555-0346', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Niko Vittorio', title: null, email: 'niko.vittorio@georgetown.edu', phone: '202-555-0347', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Orson Blakely', title: null, email: 'orson.blakely@georgetown.edu', phone: '202-555-0348', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Pierce Underwood', title: null, email: 'pierce.underwood@georgetown.edu', phone: '202-555-0349', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Rafael Domingo', title: null, email: 'rafael.domingo@georgetown.edu', phone: '202-555-0350', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Sullivan Reyes', title: null, email: 'sullivan.reyes@georgetown.edu', phone: '202-555-0351', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Tobias Ackerman', title: null, email: 'tobias.ackerman@georgetown.edu', phone: '202-555-0352', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Ulysses Cardoza', title: null, email: 'ulysses.cardoza@georgetown.edu', phone: '202-555-0353', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Victor Ramirez', title: null, email: 'victor.ramirez@georgetown.edu', phone: '202-555-0354', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Weston Hargrove', title: null, email: 'weston.hargrove@georgetown.edu', phone: '202-555-0355', status: 'sms-pending' },
  { org: 'sae', subgroup: 'brothers', name: 'Wyatt Sorensen', title: null, email: 'wyatt.sorensen@georgetown.edu', phone: '202-555-0356', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Zeke Montgomery', title: null, email: 'zeke.montgomery@georgetown.edu', phone: '202-555-0357', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Ansel Dupree', title: null, email: 'ansel.dupree@georgetown.edu', phone: '202-555-0358', status: 'joined' },
  { org: 'sae', subgroup: 'brothers', name: 'Brooks Yamamoto', title: null, email: 'brooks.yamamoto@georgetown.edu', phone: '202-555-0359', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'brothers', name: 'Corbin Leclair', title: null, email: 'corbin.leclair@georgetown.edu', phone: '202-555-0360', status: 'invited' },
  { org: 'sae', subgroup: 'brothers', name: 'Dorian Whitlock', title: null, email: 'dorian.whitlock@georgetown.edu', phone: '202-555-0361', status: 'not_on_ligo' },

  // NEW MEMBERS — 14
  { org: 'sae', subgroup: 'new-members', name: 'Asher Quinlan', title: null, email: 'asher.quinlan@georgetown.edu', phone: '202-555-0370', status: 'joined' },
  { org: 'sae', subgroup: 'new-members', name: 'Aiden Marsh', title: null, email: 'aiden.marsh@georgetown.edu', phone: '202-555-0371', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'new-members', name: 'Caleb Ostrowski', title: null, email: 'caleb.ostrowski@georgetown.edu', phone: '202-555-0372', status: 'invited' },
  { org: 'sae', subgroup: 'new-members', name: 'Dax Ferreira', title: null, email: 'dax.ferreira@georgetown.edu', phone: '202-555-0373', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'new-members', name: 'Elias Whitmore', title: null, email: 'elias.whitmore@georgetown.edu', phone: '202-555-0374', status: 'joined' },
  { org: 'sae', subgroup: 'new-members', name: 'Foster Nguyen', title: null, email: 'foster.nguyen@georgetown.edu', phone: '202-555-0375', status: 'sms-pending' },
  { org: 'sae', subgroup: 'new-members', name: 'Griffin Salas', title: null, email: 'griffin.salas@georgetown.edu', phone: '202-555-0376', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'new-members', name: 'Hudson Barrett', title: null, email: 'hudson.barrett@georgetown.edu', phone: '202-555-0377', status: 'invited' },
  { org: 'sae', subgroup: 'new-members', name: 'Isaiah Vance', title: null, email: 'isaiah.vance@georgetown.edu', phone: '202-555-0378', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'new-members', name: 'Jules Bertrand', title: null, email: 'jules.bertrand@georgetown.edu', phone: '202-555-0379', status: 'joined' },
  { org: 'sae', subgroup: 'new-members', name: 'Kieran Amado', title: null, email: 'kieran.amado@georgetown.edu', phone: '202-555-0380', status: 'sms-pending' },
  { org: 'sae', subgroup: 'new-members', name: 'Leo Mancini', title: null, email: 'leo.mancini@georgetown.edu', phone: '202-555-0381', status: 'invited' },
  { org: 'sae', subgroup: 'new-members', name: 'Mason Deverell', title: null, email: 'mason.deverell@georgetown.edu', phone: '202-555-0382', status: 'not_on_ligo' },
  { org: 'sae', subgroup: 'new-members', name: 'Nolan Ashby', title: null, email: 'nolan.ashby@georgetown.edu', phone: '202-555-0383', status: 'not_on_ligo' },
];

export const SAE_MEMBER_GROUPS = [
  { id: 'exec-board', title: 'EXEC BOARD' },
  { id: 'brothers', title: 'BROTHERS' },
  { id: 'new-members', title: 'NEW MEMBERS' },
] as const;
